

export const SET_BTC_LOADING = 'SET_BTC_LOADING'
export const CREATE_NEW_BTC_WALLET_SUCCESS = 'CREATE_NEW_BTC_WALLET_SUCCESS'
export const CREATE_NEW_BTC_WALLET_FAIL = 'CREATE_NEW_BTC_WALLET_FAIL'




export const BTC_ERROR = 'BTC_ERROR'