

export const SET_ETH_LOADING = 'SET_ETH_LOADING'
export const CREATE_NEW_ETH_WALLET_SUCCESS = 'CREATE_NEW_ETH_WALLET_SUCCESS'
export const CREATE_NEW_ETH_WALLET_FAIL = 'CREATE_NEW_ETH_WALLET_FAIL'




export const ETH_ERROR = 'ETH_ERROR'